version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11
      environment:
        GO111MODULE=on
    - image: postgres:9.5
      environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    - image: alexashley/tf-provider-custom-kong:0.0.6
      environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=localhost
      - KONG_PG_DATABASE=kong
      - KONG_PG_PASSWORD=kongdb
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stdout
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-pkg-cache
    - run:
        name: Wait for Kong to initialize
        command: |
          set -x
          sleep 20
          curl localhost:8001/status
    - run:
        name: Build
        command: make build
    - save_cache:
        key: v1-pkg-cache
        paths:
        - "/go/pkg"
    - run:
        name: Acceptance tests
        command: make testacc
    - run:
        name: Doc generation
        command: make docs
