version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Start Postgres and Kong
        command: |
          set -x
          docker-compose up -d
    - run: make build
    - run: unset GOPATH && make testacc
