version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Start Postgres and Kong
        command: |
          set -x
          docker-compose up -d
    - run:
        name: Wait for Postgres to initialize
        command: |
          for i in `seq 1 10`;
          do
            nc -z localhost 5432 && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for Postgres/Kong && exit 1
    - run: make build
    - run: make testacc
