version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11
    - image: postgres:9.5
    - image: alexashley/tf-provider-custom-kong:0.0.1
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
    - checkout
    - run:
        name: Start Postgres and Kong
        command: |
          set -x
          sleep 10
          curl localhost:8001
    - run:
        name: Build and run acceptance tests
        command: |
          curl localhost:8001/status
          make build
          make testacc
