version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Start Postgres and Kong
        command: |
          set -x
          docker-compose up -d
          sleep 10
          docker run --network container:kong \
            appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8001/status
    - run:
        name: Build and run acceptance tests
        command: |
          curl localhost:8001/status
          make build
          make testacc
